# Generated by Django 4.2.4 on 2023-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
