# Generated by Django 4.2.4 on 2023-09-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0003_budget_user_expense_user_income_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
